### ISSUE TITLE
could not import redmax_py

### ISSUE THREAD

**Issue by Navneet-Kaur21** [eanswer/TactileSimulation#5]
I have tried installing using the source and the docker method. (For both DiffHand and TactileSimulation)
I keep getting the same error again and again. Could you please help solving this?

Traceback (most recent call last):
  File "test_sim_speed.py", line 13, in <module>
    import redmax_py as redmax
ModuleNotFoundError: No module named 'redmax_py'

**Comment by eanswer** [comment]
Did you install DiffRedMax successfully (Step 4 in README instruction):

```
cd externals/DiffHand/core
python setup.py install
```

After you successfully install it, you should be able to import redmax_py in your conda environment.

**Comment by Navneet-Kaur21** [comment]
Hi Jie

Yes, I did. Here is the screenshot of the output after running the install
command.
[image: image.png]

**Comment by Navneet-Kaur21** [comment]
![Screenshot from 2023-11-17 09-49-00](https://github.com/eanswer/TactileSimulation/assets/66468443/0f395954-58c9-4832-b6b4-8158c810ca9c)

**Comment by Navneet-Kaur21** [comment]
![Screenshot from 2023-11-17 09-49-00~2](https://github.com/eanswer/TactileSimulation/assets/66468443/a78a5a55-4071-4dd9-859a-b1c7768d73a7)

**Comment by Navneet-Kaur21** [comment]
I have followed the instructions in the README file. (docker and source both). In both the cases it gives the same error.

**Comment by eanswer** [comment]
That's strange. I just tried to install the codebase from scratch and it works for me. Right after you install `redmax_py` and open a python session in your command line, could you run `import redmax_py`?
![image](https://github.com/eanswer/TactileSimulation/assets/15688188/cc9efeaf-71c2-4d62-8a4d-a84d723e79f8)

**Comment by Navneet-Kaur21** [comment]
On running import redmax_py I get this:
![Screenshot from 2023-11-17 10-33-22](https://github.com/eanswer/TactileSimulation/assets/66468443/1eb440d9-2910-418f-ab0e-5aba7c84ab0f)

**Comment by eanswer** [comment]
I see, could you check two things for me:

1. Which python path you are using, run below in terminal
```
which python
```

2. Check whether redmax_py is installed in your conda environment:
```
pip list | grep redmax-py
```

**Comment by eanswer** [comment]
May be also `which pip`

**Comment by Navneet-Kaur21** [comment]
1. /home/anaconda3/bin/python
2. returns nothing. 
3. /home/anaconda3/bin/pip

**Comment by Navneet-Kaur21** [comment]
Also, I am attaching the full output of `python setup.py install`



running install
/home/navneetkaur/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/navneetkaur/anaconda3/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing redmax_py.egg-info/PKG-INFO
writing dependency_links to redmax_py.egg-info/dependency_links.txt
writing top-level names to redmax_py.egg-info/top_level.txt
reading manifest file 'redmax_py.egg-info/SOURCES.txt'
writing manifest file 'redmax_py.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at /home/navneetkaur/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/FindOpenGL.cmake:381 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
CMake Deprecation Warning at externals/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at externals/pugixml/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at externals/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.6.0 dev1
CMake Warning (dev) at externals/pybind11/tools/FindPythonLibsNew.cmake:96 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  externals/pybind11/tools/pybind11Tools.cmake:38 (find_package)
  externals/pybind11/tools/pybind11Common.cmake:195 (include)
  externals/pybind11/CMakeLists.txt:162 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /home/navneetkaur/anaconda3/bin/python (found version "3.11.5") 
-- Found PythonLibs: /home/navneetkaur/anaconda3/lib/libpython3.11.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
CMake Deprecation Warning at externals/glfw/CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at externals/glfw/CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0042 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Vulkan: /usr/lib/x86_64-linux-gnu/libvulkan.so  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Using X11 for window creation
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done (2.5s)
-- Generating done (0.2s)
-- Build files have been written to: /home/navneetkaur/TactileSimulation/externals/DiffHand/core/build/temp.linux-x86_64-cpython-311
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying redmax_py.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying redmax_py.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying redmax_py.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying redmax_py.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying redmax_py.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/redmax_py-0.0.1-py3.11-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing redmax_py-0.0.1-py3.11-linux-x86_64.egg
creating /home/navneetkaur/anaconda3/lib/python3.11/site-packages/redmax_py-0.0.1-py3.11-linux-x86_64.egg
Extracting redmax_py-0.0.1-py3.11-linux-x86_64.egg to /home/navneetkaur/anaconda3/lib/python3.11/site-packages
Adding redmax-py 0.0.1 to easy-install.pth file

Installed /home/navneetkaur/anaconda3/lib/python3.11/site-packages/redmax_py-0.0.1-py3.11-linux-x86_64.egg
Processing dependencies for redmax-py==0.0.1
Finished processing dependencies for redmax-py==0.0.1

**Comment by eanswer** [comment]
It seems that you are not in your conda env as shown in the python and pip path

**Comment by Navneet-Kaur21** [comment]
Okay. Here are the results in the env:
1. /home/navneetkaur/anaconda3/envs/tactile_control_env/bin/python
2. redmax-py                     0.0.1
3. /home/navneetkaur/anaconda3/envs/tactile_control_env/bin/pip

**Comment by eanswer** [comment]
Then it seems you have installed redmax_py. Can you import it if you open a python via `/home/navneetkaur/anaconda3/envs/tactile_control_env/bin/python`

**Comment by Navneet-Kaur21** [comment]
Uhh no.
(tactile_control_env) navneetkaur@navneet:~/TactileSimulation/externals/DiffHand/core$ /home/navneetkaur/anaconda3/envs/tactile_control_env/bin/python
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redmax_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'redmax_py'

**Comment by eanswer** [comment]
that's so weird, I'm sorry that I have no other ideas about what went wrong...

**Comment by Navneet-Kaur21** [comment]
I tried it with a different pc. It is giving the same error. Could there be anything missing in the installation? Some prerequisites that I need before I can install it successfully?

**Comment by Runze-Zhao** [comment]
I have run into the same issue

**Comment by Navneet-Kaur21** [comment]
could you please let me know if you figure it out @Runze-Zhao 

> I have run into the same issue

**Comment by Navneet-Kaur21** [comment]
also, @eanswer could you share the folder - `anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/redmax_py-0.0.1-py3.8-linux-x86_64.egg` or what files should it contain.

**Comment by Runze-Zhao** [comment]
> could you please let me know if you figure it out @Runze-Zhao
> 
> > I have run into the same issue

The problem on my side is that I don't recursively have to download all the folders under the project (DiffHand/pybind11),also lack  of the package of libXxf86vm.After downloading the relevant files, re-run the setup.py and it will work fine.
I hope that helps.

**Comment by eanswer** [comment]
@Navneet-Kaur21 Let me know if the issue has been successfully solved by recursively cloning the project as mentioned by @Runze-Zhao so that I can close the issue.

**Comment by LZC0113** [comment]
Hello, I have run into the same issue. I cannot  even install the 'redmax_py' pkg.

**Comment by LZC0113** [comment]
> Hello, I have run into the same issue. I cannot even install the 'redmax_py' pkg.

I solve the problem by rebuilding the environment and now it works lol. Some packages must be missing when first time install the env.

**Comment by cidxb** [comment]
I ran into the same problem too.

First of all, i was using the docker image, since i got trouble by installation on
 `cd core python setup.py install`
So i running it on the docker image instead.

And I after I got in the image, i used pip install -e . in the path /DiffHand/core/ . 
I don't know if it is right practice, since if i not install it, I can't import it in the python environment or find

Then there will be 
 `Preparing metadata (setup.py) ... done`
 `Installing collected packages: redmax-py`
 `Running setup.py develop for redmax-py`
and
```
Installing collected packages: redmax-py
Running setup.py develop for redmax-py
Successfully installed redmax-py
```
Then if i enter python into the python command line, 
i can **_successfully import redmax_py_**.  But if I run the example script, the same old ModuleNotFoundError: No module named 'redmax_py' error will appear.
So i import os, use commend line `path=os.path.abspath(redmax_py.__file__)  print(path)`
And it shows _**/workspace/DiffHand/core/redmax_py.cpython-37m-x86_64-linux-gnu.so**_


It this in order? So the solution maybe add this path into the package searching path or environment path?


Also I found that in the image, the package actually installed in the following path:
```
/usr/lib/python3.7/site-packages# ls
easy-install.pth  redmax_py-0.0.1-py3.7-linux-x86_64.egg
```
But the rest of the pip and the using python is from 
```
/usr/bin/python
/usr/local/bin/pip
```
