### ISSUE TITLE
TypeError: reset() got an unexpected keyword argument 'seed' TypeError: reset() got an unexpected keyword argument 'seed'

### ISSUE THREAD

**Issue by ZHANG-Xiaoshi** [eanswer/TactileSimulation#7]
I just install the repo as the instructions, however i encontered a problem as following
joint order : 0 1 2 3 4 5 6 7 8 9 10 11 12 
Process ForkServerProcess-3:
Process ForkServerProcess-2:
Process ForkServerProcess-4:
Process ForkServerProcess-1:
Process ForkServerProcess-5:
Process ForkServerProcess-7:
Process ForkServerProcess-8:
Process ForkServerProcess-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
TypeError: reset() got an unexpected keyword argument 'seed'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
TypeError: reset() got an unexpected keyword argument 'seed'
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
TypeError: reset() got an unexpected keyword argument 'seed'
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 140, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/core.py", line 427, in reset
    return self.env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/gym/utils/passive_env_checker.py", line 200, in env_reset_passive_checker
    result = env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
TypeError: reset() got an unexpected keyword argument 'seed'
Traceback (most recent call last):
  File "/home/stephen/TactileSimulation/examples/TactileInsertionExp/train_tactile_insertion_ppo.py", line 45, in <module>
    algo.train()
  File "/home/stephen/TactileSimulation/algorithms/ppo_rnn.py", line 124, in train
    obs = self.envs.reset()
  File "/home/stephen/TactileSimulation/externals/pytorch-a2c-ppo-acktr-gail/a2c_ppo_acktr/envs.py", line 188, in reset
    obs = self.venv.reset()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 137, in reset
    results = [remote.recv() for remote in self.remotes]
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/stephen/anaconda3/envs/tactile_control_env/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Process finished with exit code 1
It seems the problem with gym but i tried some different versions and still get the same result

**Comment by Shimadawallace** [comment]
This problem could be caused by wrong version of pip and setuptools. Try "pip install setuptools==65.5.0 pip==21" and downgrading stable-baselines3 to 1.8.0.

**Comment by eanswer** [comment]
@ZHANG-Xiaoshi  Let me know if the issue has been successfully solved by downgrading the stable-baseline as mentioned by @Shimadawallace  so that I can close the issue.

**Comment by huangjiekaiming** [comment]
Would you like to consult everyone to solve this problem? I'm still looking for a solution
